In [1]:
from trading import *

In [2]:
case = Trading()
case.close

,095570,006840,027410,282330,138930,001460,001465,001040,079160,00104K,...,066330,032590,042570,058680,012460,012990,014827,032710,015670,015675
Date,,,,,,,,,,,,,,,,,,,,,
1990-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-09-27,5980.0,27300.0,6200.0,174500.0,8260.0,472500.0,188500.0,100500.0,29350.0,82000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-28,5900.0,27050.0,6050.0,173000.0,8590.0,456000.0,185000.0,99900.0,29100.0,81800.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-29,5850.0,26700.0,5970.0,173000.0,8580.0,446500.0,183000.0,98000.0,29600.0,80800.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-30,5840.0,26950.0,5980.0,170500.0,8840.0,444500.0,186000.0,98800.0,29700.0,81700.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-10-01,5770.0,26800.0,5680.0,171000.0,8810.0,432500.0,184500.0,97100.0,29200.0,80800.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# 변수 저장, 불러오기a

In [ ]:
def defineUniverse()

In [ ]:
def makeResult()

In [ ]:
def searchByTarget(targetStrategy : str, targetGroup : str=None, targetPeriodStart : datetime=None, targetPeriodEnd : datetime=None):
    
    if not 
    if (targetStrategy == "ma"
        
        movingAverage = dfChange['Close'].rolling(daysForMABuy).mean()


    listStockCode
    listDateBuy

# 나중에 일자별로도 분리할 수 있도록.
    return pd.DataFrame({stock_code':listStockCode, 'date':listDateBuy})